### ISSUE TITLE
作者标题疑似爬错

### ISSUE THREAD

**Issue by tzcawa** [poem-snake/poem-snake#2]
![](https://s4.ax1x.com/2022/03/04/bUjjJ0.png)

（图片地址 <https://s4.ax1x.com/2022/03/04/bUjjJ0.png>）

显然此诗作者是李白，估计是爬错了地方。

但当回答 `我寄愁心与明月，随风直到夜郎西。` 时作者就是李白（

**Comment by william-song-shy** [comment]
这个是已知问题
