### ISSUE TITLE
建议使用子串判断诗句重复

### ISSUE THREAD

**Issue by tzcawa** [poem-snake/poem-snake#3]
~~别问我是怎么一天发现2 bugs的（~~

比如当题目是 `时霎清明，载花不过西园路。` 时，

回答 `时霎清明，载花不过西园路。嫩阴绿树。正是春留处。` 就可以一遍把整首诗搞掉（

**Comment by william-song-shy** [comment]
感谢反馈，确实是个恶性 bug

**Comment by william-song-shy** [comment]
fixed in https://github.com/william-song-shy/poem-snake/commit/6da256a9666dbed24dbe7bfd5c35ec90f3117c46
